version: '3.8'

services:
  mysql:
    container_name: kitaq_mysql
    build: ../DB
    ports:
      - "3306:3306"
    volumes:
      - ../DB/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    platform: linux/x86_64
  flask:
    build: ../Backend/
    ports:
      - "49152:5000"
    container_name: flask
    volumes:
       - ../Backend/:/usr/src/app
    command: flask run --host=0.0.0.0

volumes:
  mysql-data:
    name: kitaq-volume
