version: '3.9'

services:
  mysql:
    container_name: kitaq_mysql
    build: ../DB
    ports:
      - "3306:3306"
    volumes:
      - ../DB/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    platform: linux/x86_64

volumes:
  mysql-data:
    name: kitaq-volume

networks:
  kitaq_network:
    external: true
