version: '3.9'

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ../DB/Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - 3306:3306
    env_file:
      - ../DB/.env_mysql
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ../DB/init
        target: /docker-entrypoint-initdb.d

volumes:
  mysql-data:
    name: mysql-volume