name: CI
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SK }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd kitaQ-teamC/
            echo ${{secrets.SUDO_PASSWORD}} | sudo -S make down
            git pull
            echo ${{secrets.SUDO_PASSWORD}}  | sudo -S make build
            echo ${{secrets.SUDO_PASSWORD}}  | sudo -S make up
